name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull hariharansdeveloper/leaf_reminder_api:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f leaf_reminder_api-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name leaf_reminder_api-container hariharansdeveloper/leaf_reminder_api
